---
title: ''
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,
                      message = FALSE,
                      warning = FALSE)
```


```{r}

library(tidyverse)
library(here)
library(AICcmodavg)
library(flextable)
library(ftExtra)
library(officer)
```

```{r}
get_coef_ci <- function(zmod, zmod.name) {
zmod_coefCI <- cbind(coef(zmod), confint(zmod)) %>% 
  data.frame() %>% 
  rename(est = 1, lci = 2, uci = 3) %>% 
  rownames_to_column("varb") %>% 
  mutate(mod = zmod.name) %>% 
  mutate(varb = ifelse(varb %in% c("weight.slope40", "tibiotar.slope35", "flipper.slope40"), "growth", varb)) %>% 
  filter(varb != "(Intercept)") %>% 
  mutate(across(c(est, lci, uci), ~format(round(., 2), nsmall = 2))) %>% 
  mutate(across(c(est, lci, uci), ~trimws(.))) %>% 
  mutate(coef.ci = paste(est, " (", lci, "; ", uci, ")", sep = "")) %>% 
  select(mod, varb, coef.ci) %>% 
  pivot_wider(id_cols = mod, names_from = varb, values_from = coef.ci) %>% 
  mutate(adj.r2 = summary(zmod)$adj.r.squared,
         adj.r2 = format(round(adj.r2, 2), nsmall = 2))
}
```



```{r }
# creching age output from best models ----
cr_age_step2_mods <- readRDS(here("fitted_models/cr_timing/cr_age_step2_mods"))

cr_age_mod_tab <- aictab(cr_age_step2_mods, names(cr_age_step2_mods)) %>% 
  data.frame() %>% 
  mutate(Delta_AICc = round(Delta_AICc, 2))

cr_age_best_mods <- cr_age_mod_tab %>%  
  filter(Delta_AICc < 4)

cr_age_next_best <- cr_age_mod_tab %>%  
  filter(Delta_AICc > 4) %>% 
  filter(Delta_AICc == min(Delta_AICc))


# coefficients, R2

get_cr_age_coefCI_lm <- function(zmod.name) {
  zmod <- cr_age_step2_mods[zmod.name][[1]]
zmod_coefCI <- get_coef_ci(zmod, zmod.name)
}


cr_age_coefCI <- map_df(cr_age_best_mods$Modnames, get_cr_age_coefCI_lm) %>%
  rename(Modnames = mod) %>% 
  full_join(cr_age_best_mods) %>% 
  arrange(Delta_AICc) %>% 
  dplyr::select(Modnames, resid.hatch, growth, SEASON1314, Delta_AICc, adj.r2) %>% 
  mutate(Modnames = gsub("_", " + ", Modnames),
         Modnames = gsub("hatch", "hatch date", Modnames),
         Modnames = gsub("mass", "mass growth", Modnames),
         Modnames = gsub("tib", "tibiotarsus growth", Modnames),
         Modnames = gsub("flip", "flipper growth", Modnames)
         )

```
<br>
Creching age  
```{r}

flextable(cr_age_coefCI) %>% 
  add_header_row(values = c("", "Estimated coeficients (95% CI)", ""), colwidths = c(1, 3, 2)) %>% 
  set_header_labels(Modnames = "Model structure",
                    resid.hatch = "Hatch date",
                    SEASON1314 = "Year",
                    growth = "Growth rate",
                    Delta_AICc = "\u0394 AICc") %>% 
  compose(i = 2, j = "adj.r2", part = "header",
    value = as_paragraph(
      "Adj. R",
      as_sup("2")
    ) ) %>% 
  border_remove() %>% 
  border(i = 2, j = 2:4, border.top = fp_border(color = "black"), part = "header") %>% 
  border(i = 1, border.top = fp_border(color = "black"), part = "header") %>% 
  border(i = 1, border.top = fp_border(color = "black"), part = "body") %>% 
  border(i = 4, border.bottom = fp_border(color = "black"), part = "body") %>%
  width(1, width = 2.7) %>% 
  width(2:4, width = 1.6) %>% 
  width(5:6, width = 0.5) %>% 
  fit_to_width(max_width = 7.5) %>% 
  align(j = 2:6, align = "center", part = "all") %>% 
  footnote(i = 2, j = 5, part = "header", value = as_paragraph(paste("next best model \u0394 AICc = ", cr_age_next_best$Delta_AICc[[1]])))%>% 
  colformat_md() %>% 
  fontsize(size = 9, part = "footer")

```



```{r}

cr_mass_step2_mods <- readRDS(here("fitted_models/cr_timing/cr_mass_step2_mods"))

cr_mass_mod_tab <- aictab(cr_mass_step2_mods, names(cr_mass_step2_mods)) %>% 
  data.frame() %>% 
  mutate(Delta_AICc = round(Delta_AICc, 2))

cr_mass_best_mods <- cr_mass_mod_tab %>%  
  filter(Delta_AICc < 4) %>% 
  arrange(Delta_AICc)

cr_mass_next_best <- cr_mass_mod_tab %>%  
  filter(Delta_AICc > 4) %>% 
  filter(Delta_AICc == min(Delta_AICc))

# coefficients, R2
get_cr_mass_coefCI_lm <- function(zmod.name) {
  zmod <- cr_mass_step2_mods[zmod.name][[1]]
zmod_coefCI <- get_coef_ci(zmod, zmod.name)
}

cr_mass_coefCI <- map_df(cr_mass_best_mods$Modnames, get_cr_mass_coefCI_lm) %>%
  rename(Modnames = mod) %>% 
  full_join(cr_mass_best_mods) %>% 
  arrange(Delta_AICc) %>% 
  dplyr::select(Modnames, cr.age, growth, sexM, SEASON1314, Delta_AICc, adj.r2) %>% 
  mutate(Modnames = gsub("_", " + ", Modnames),
         Modnames = gsub("hatch", "hatch date", Modnames),
         Modnames = gsub("mass.", "", Modnames),
         Modnames = gsub("growth", "mass growth", Modnames)
         )


```



```{r}

cr_flip_step2_mods <- readRDS(here("fitted_models/cr_timing/cr_flip_step2_mods"))

cr_flip_mod_tab <- aictab(cr_flip_step2_mods, names(cr_flip_step2_mods)) %>% 
  data.frame() %>% 
  mutate(Delta_AICc = round(Delta_AICc, 2))

cr_flip_best_mods <- cr_flip_mod_tab %>%  
  filter(Delta_AICc < 4) %>% 
  arrange(Delta_AICc)

cr_flip_next_best <- cr_flip_mod_tab %>%  
  filter(Delta_AICc > 4) %>% 
  filter(Delta_AICc == min(Delta_AICc))

# coefficients, R2
get_cr_flip_coefCI_lm <- function(zmod.name) {
  zmod <- cr_flip_step2_mods[zmod.name][[1]]
zmod_coefCI <- get_coef_ci(zmod, zmod.name)

}

cr_flip_coefCI <- map_df(cr_flip_best_mods$Modnames, get_cr_flip_coefCI_lm) %>%
  rename(Modnames = mod) %>% 
  full_join(cr_flip_best_mods) %>% 
  arrange(Delta_AICc) %>% 
  dplyr::select(Modnames, cr.age, growth, SEASON1314, Delta_AICc, adj.r2) %>% 
  mutate(Modnames = gsub("_", " + ", Modnames),
         Modnames = gsub("hatch", "hatch date", Modnames),
         Modnames = gsub("flip.", "", Modnames),
         Modnames = gsub("growth", "flipper growth", Modnames)
         )


```

```{r}

cr_tib_step2_mods <- readRDS(here("fitted_models/cr_timing/cr_tib_step2_mods"))

cr_tib_mod_tab <- aictab(cr_tib_step2_mods, names(cr_tib_step2_mods)) %>% 
  data.frame() %>% 
  mutate(Delta_AICc = round(Delta_AICc, 2))

cr_tib_best_mods <- cr_tib_mod_tab %>%  
  filter(Delta_AICc < 4) %>% 
  arrange(Delta_AICc)

cr_tib_next_best <- cr_tib_mod_tab %>%  
  filter(Delta_AICc > 4) %>% 
  filter(Delta_AICc == min(Delta_AICc))

# coefficients, R2
get_cr_tib_coefCI_lm <- function(zmod.name) {
  zmod <- cr_tib_step2_mods[zmod.name][[1]]
zmod_coefCI <- get_coef_ci(zmod, zmod.name)
}

cr_tib_coefCI <- map_df(cr_tib_best_mods$Modnames, get_cr_tib_coefCI_lm) %>%
  rename(Modnames = mod) %>% 
  full_join(cr_tib_best_mods) %>% 
  arrange(Delta_AICc) %>% 
  dplyr::select(Modnames, cr.age, growth, SEASON1314, Delta_AICc, adj.r2) %>% 
  mutate(Modnames = gsub("_", " + ", Modnames),
         Modnames = gsub("hatch", "hatch date", Modnames),
         Modnames = gsub("tib.", "", Modnames),
         Modnames = gsub("growth", "tibiotarsus growth", Modnames)
         )


```



```{r}

cr_size_out_table <- rbind(
  # mass rows
  data.frame(Modnames = "Competitive creching mass model", cr.age = "", growth = "", sexM = "", SEASON1314 = "", Delta_AICc = "", adj.r2 = ""),
  cr_mass_coefCI,
  data.frame(Modnames = paste("next best model \u0394 AICc = ", cr_mass_next_best$Delta_AICc[[1]]), cr.age = "", growth = "", sexM = "", SEASON1314 = "", Delta_AICc = "", adj.r2 = ""),
  # flipper rows
  data.frame(Modnames = "Competitive creching flipper length model", cr.age = "", growth = "", sexM = "", SEASON1314 = "", Delta_AICc = "", adj.r2 = ""),
  cr_flip_coefCI %>% mutate(sexM = NA),
  data.frame(Modnames = paste("next best model \u0394 AICc = ", cr_mass_next_best$Delta_AICc[[1]]), cr.age = "", growth = "", sexM = "", SEASON1314 = "", Delta_AICc = "", adj.r2 = ""),
    # tib rows
    data.frame(Modnames = "Competitive creching tibiotarsus length models", cr.age = "", growth = "", sexM = "", SEASON1314 = "", Delta_AICc = "", adj.r2 = ""),
  cr_tib_coefCI %>% mutate(sexM = NA),
  data.frame(Modnames = paste("next best model \u0394 AICc = ", cr_mass_next_best$Delta_AICc[[1]]), cr.age = "", growth = "", sexM = "", SEASON1314 = "", Delta_AICc = "", adj.r2 = "")
)

```
   
<br>
<br>
   

Creching size  
```{r}

flextable(cr_size_out_table) %>% 
  add_header_row(values = c("", "Estimated coeficients (95% CI)", ""), colwidths = c(1, 4, 2)) %>% 
  set_header_labels(Modnames = "Model structure",
                    cr.age = "Creching age",
                    sexM = "Sex",
                    SEASON1314 = "Year",
                    growth = "Growth rate",
                    Delta_AICc = "\u0394 AICc") %>% 
  compose(i = 2, j = "adj.r2", part = "header",
    value = as_paragraph(
      "Adj. R",
      as_sup("2")
    ) ) %>% 
  border_remove() %>% 
  border(i = 1, border.top = fp_border(color = "black"), part = "header") %>% # header top border
  border(i = 1, j = 2:5, border.bottom = fp_border(color = "black"), part = "header") %>% # coefs cols border bottom
  border(i = 2, border.bottom = fp_border(color = "black"), part = "header") %>% # header border bottom
  border(i = 1, j = 1, border.bottom = fp_border(color = "black"), part = "body") %>% # mass top sub border
  border(i = 2 + nrow(cr_mass_coefCI), border.bottom = fp_border(color = "black"), part = "body") %>% # mass bottom border
  border(i = 1 + 2 + nrow(cr_mass_coefCI), j = 1, border.bottom = fp_border(color = "black"), part = "body") %>% # flipper top sub border
  border(i = 2 + nrow(cr_mass_coefCI) + 2 + nrow(cr_flip_coefCI), border.bottom = fp_border(color = "black"), part = "body") %>% # flipper bottom border
  border(i = 1 + 2 + nrow(cr_mass_coefCI)+ 2 + nrow(cr_flip_coefCI), j = 1, border.bottom = fp_border(color = "black"), part = "body") %>% # tib top sub border
  border(i = 2 + nrow(cr_mass_coefCI) + 2 + nrow(cr_flip_coefCI) + 2 + nrow(cr_tib_coefCI), border.bottom = fp_border(color = "black"), part = "body") %>% # tib bottom border
  width(1, width = 2.7) %>% 
  width(2:5, width = 1.5) %>% 
  width(6:7, width = 0.5) %>% 
  fit_to_width(max_width = 7.5) %>% 
  align(j = 2:6, align = "center", part = "all") %>% 
  colformat_md()%>% 
  fontsize(size = 9, part = "all")

```
