---
title: ''
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,
                      message = FALSE,
                      warning = FALSE)
```


```{r}

library(tidyverse)
library(here)
library(AICcmodavg)
library(flextable)
library(ftExtra)
library(officer)
library(RMark)

options(scipen = 999)
```

```{r}
get_coef_ci <- function(zmod, zmod.name) {
zmod_coefCI <- cbind(coef(zmod), confint(zmod)) %>% 
  data.frame() %>% 
  rename(est = 1, lci = 2, uci = 3) %>% 
  rownames_to_column("varb") %>% 
  mutate(mod = zmod.name) %>% 
  mutate(varb = ifelse(varb %in% c("weight.slope40", "tibiotar.slope35", "flipper.slope40"), "growth", varb)) %>% 
  filter(varb != "(Intercept)") %>% 
  mutate(across(c(est, lci, uci), ~format(round(., 2), nsmall = 2))) %>% 
  mutate(across(c(est, lci, uci), ~trimws(.))) %>% 
  mutate(coef.ci = paste(est, " (", lci, "; ", uci, ")", sep = "")) %>% 
  select(mod, varb, coef.ci) %>% 
  pivot_wider(id_cols = mod, names_from = varb, values_from = coef.ci) %>% 
  mutate(adj.r2 = summary(zmod)$adj.r.squared,
         adj.r2 = format(round(adj.r2, 2), nsmall = 2))
}

multi_mod_coefs <- function(mods) {
  
coefCI <- map2_df(mods[-length(mods)], names(mods[-length(mods)]), get_coef_ci) %>%
  rename(Modnames = mod) %>% 
  full_join(mods$model.table) %>%  
  filter(Delta_AICc < 4) %>% 
  arrange(Delta_AICc)%>% 
  mutate(Delta_AICc = round(Delta_AICc, 2)) %>% 
  dplyr::select(-Modnames, -ModelLik, -AICcWt, -LL, -Cum.Wt, -AICc, -K)
}


coef_outtable <- function(coefCI_tab) {
  
flextable(coefCI_tab) %>% 
  add_header_row(values = c("", "Estimated coefficients (95% CI)", ""), colwidths = c(1, (ncol(coefCI_tab) - 3), 2)) %>% 
  set_header_labels(model.structure = "Model structure",
                    resid.hatch = "Hatch date",
                    SEASON1314 = "Year",
                    growth = "Growth rate",
                    Delta_AICc = "\u0394 AICc",
                    sexM = "Sex",
                    cr.age = paste("Cr", "\u00E8", "ching age", sep = "")) %>% 
  compose(i = 2, j = "adj.r2", part = "header",
    value = as_paragraph(
      "Adj. R",
      as_sup("2")
    ) ) %>% 
  border_remove() %>% 
  border(i = 2, j = 2:(ncol(coefCI_tab)-2), border.top = fp_border(color = "black"), part = "header") %>% 
  border(i = 1, border.top = fp_border(color = "black"), part = "header") %>% 
  border(i = 1, border.top = fp_border(color = "black"), part = "body") %>% 
  border(i = nrow(coefCI_tab), border.bottom = fp_border(color = "black"), part = "body") %>%
  width(1, width = 2) %>% 
  width(2:(ncol(coefCI_tab)-2), width = 1.6) %>% 
  width((ncol(coefCI_tab)-1):ncol(coefCI_tab), width = 0.6) %>% 
  fit_to_width(max_width = 7.5) %>% 
  align(j = 2:ncol(coefCI_tab), align = "center", part = "all")
  #colformat_md() 

}

```


<br>
Creching age
```{r }
# creching age output from best models ----


cr_age_coefCI <- readRDS(here("fitted_models/cr_timing/cr_age_step2_mods")) %>% 
  multi_mod_coefs() %>% 
  dplyr::select(model.structure, SEASON1314, resid.hatch, growth, Delta_AICc, adj.r2) 

coef_outtable(cr_age_coefCI)

```


<br>
<br>
   

Creching size  
```{r}

cr_mass_coefCI <- readRDS(here("fitted_models/cr_timing/cr_mass_step2_mods")) %>% 
  multi_mod_coefs() %>% 
  select(-sexM) # uninformative 

cr_flip_coefCI <- readRDS(here("fitted_models/cr_timing/cr_flip_step2_mods")) %>% 
  multi_mod_coefs()

cr_tib_coefCI <- readRDS(here("fitted_models/cr_timing/cr_tib_step2_mods")) %>% 
  multi_mod_coefs() 

cr_size_out_table <- bind_rows(
  # mass rows
  data.frame(model.structure = paste("Cr", "\u00E8", "ching mass", sep = "")),
  cr_mass_coefCI,
  # flipper rows
  data.frame(model.structure = paste("Cr", "\u00E8", "ching flipper length", sep = "")),
  cr_flip_coefCI,
    # tib rows
    data.frame(model.structure = paste("Cr", "\u00E8", "ching tibiotarsus length", sep = "")),
  cr_tib_coefCI) %>% 
  select(model.structure, SEASON1314, resid.hatch, growth, cr.age, Delta_AICc, adj.r2)

cr_size_out_table <- cr_size_out_table %>% 
  mutate(across(names(cr_size_out_table[2:ncol(cr_size_out_table)]), ~ifelse(grepl("model", model.structure) & is.na(.), "", .)))

coef_outtable(cr_size_out_table) %>% 
  border(i = 1, j = 1, border.bottom = fp_border(color = "black"), part = "body") %>% # mass top partial
  border(i = 1 + nrow(cr_mass_coefCI), border.bottom = fp_border(color = "black"), part = "body") %>% # mass bottom border
  border(i = 2 + nrow(cr_mass_coefCI), j = 1, border.bottom = fp_border(color = "black"), part = "body") %>% # flipper top partial
  border(i = 1 + nrow(cr_mass_coefCI) + 1 + nrow(cr_flip_coefCI), border.bottom = fp_border(color = "black"), part = "body") %>% # flipper bottom border
  border(i = 1 + nrow(cr_mass_coefCI)+ 2 + nrow(cr_flip_coefCI), j = 1, border.bottom = fp_border(color = "black"), part = "body") # tib top partial
```
   

<br>
<br>

Creche period survival
```{r }
# creching age output from best models ----
cr_age_size_surv <- readRDS(here("fitted_models/survival/step6_cr_timing_surv"))

cr_age_size_surv_tab <- cr_age_size_surv$model.table

int_deviance <- readRDS(here("fitted_models/survival/step5.2_creched_phi"))$phi.int_p.sat$results$deviance

get_phi_betas <- function(zmod.name) {
  zmod <- cr_age_size_surv[zmod.name]
  betas <- zmod[[1]]$results$beta %>% 
    data.frame() %>% 
    rownames_to_column("coef") %>% 
    mutate(model = zmod[[1]]$model.name,
           mod.name = names(zmod),
           dev.expl = zmod[[1]]$results$deviance) %>% 
    filter(grepl("Phi", coef), !grepl("Intercept", coef))
}

betas <- map_df(names(cr_age_size_surv), get_phi_betas)

aic_betas <- full_join(cr_age_size_surv_tab %>% select(model, phi.stru, DeltaQAICc), betas) %>% 
  filter(DeltaQAICc < 2)

aic_beta_table <- aic_betas %>% 
  select(-model, -se) %>% 
  rename(est = estimate, lci = lcl, uci = ucl) %>% 
  mutate(coef = gsub("Phi\\:", "", coef),
         coef = gsub("SEASON1314", "Yr", coef),
         coef = gsub("log\\(Time \\+ 1\\)", "Time", coef),
         coef = gsub("Time", "Time", coef),
         coef = ifelse(grepl("cr\\.", coef), "Cr.size", coef)) %>% 
  #mutate(across(c(est, lci, uci), ~format(round(., 4), nsmall = 4))) %>% 
   mutate(across(c(est, lci, uci), 
             ~ case_when(coef %in% c("Yr", "Time") ~ format(round(., 2), nsmall = 2),
                         coef == "Cr.size" ~ format(round(., 3), nsmall = 3)))) %>% 
  mutate(across(c(est, lci, uci), ~trimws(.))) %>% 
  mutate(coef.ci = paste(est, " (", lci, "; ", uci, ")", sep = ""),
         DeltaQAICc = round(DeltaQAICc, 2)) %>% 
  pivot_wider(id_cols = c(phi.stru, DeltaQAICc), names_from = coef, values_from = coef.ci) %>% 
  relocate(Cr.size, .after = last_col()) %>% 
  relocate(DeltaQAICc, .after = last_col())

flextable(aic_beta_table) %>% 
  add_header_row(values = c("", "Estimated coefficients (95% CI)", ""), colwidths = c(1, 3, 1)) %>% 
  set_header_labels(phi.stru = "Model structure",
                    Time = "Time\n(TT or lnT)",
                    Cr.size = "Creching size\n(flipper, mass or tibio)",
                    DeltaQAICc = "\u0394 QAICc"
                    ) %>% 
  border_remove() %>% 
  border(i = 1, border.top = fp_border(color = "black"), part = "header") %>% # header top border
  border(i = 1, j = 2:4, border.bottom = fp_border(color = "black"), part = "header") %>% # coefs cols border bottom
  border(i = 2, border.bottom = fp_border(color = "black"), part = "header") %>% # header border bottom
  border(i = nrow(aic_beta_table), border.bottom = fp_border(color = "black"), part = "body") %>% # mass top sub border
  width(1, width = 2.5) %>% 
  width(2:4, width = 1.5) %>% 
  width(5, width = 0.6) %>% 
  fit_to_width(max_width = 7.5) %>% 
  autofit() %>% 
  align(j = 2:5, align = "center", part = "all") 
  #colformat_md() 

```